const types = {
  CREATE_USER: "CREATE_USER",
  THROW_SIGN_UP_ERRORS: "THROW_SIGN_UP_ERRORS",
  REMOVE_SIGN_UP_ERRORS: "REMOVE_SIGN_UP_ERRORS",
  LOGIN_USER: "LOGIN_USER",
  THROW_LOGIN_ERROR: "THROW_LOGIN_ERROR",
  REMOVE_LOGIN_ERROR: "REMOVE_LOGIN_ERROR",
  LOGOUT_USER: "LOGOUT_USER",
  THROW_LOGOUT_ERROR: "THROW_LOGOUT_ERROR",
  REMOVE_LOGOUT_ERROR: "REMOVE_LOGOUT_ERROR",
  GET_MY_PROFILE: "GET_MY_PROFILE",
  FETCH_ALL_TASKS: "FETCH_ALL_TASKS",
  THROW_TASK_CREATION_ERROR: "THROW_TASK_CREATION_ERROR",
  REMOVE_TASK_CREATION_ERROR: "REMOVE_TASK_CREATION_ERROR",
  ADD_RECENTLY_COMPLETED: "ADD_RECENTLY_COMPLETED",
  REMOVE_RECENTLY_COMPLETED: "REMOVE_RECENTLY_COMPLETED",
};

export default types;
