const types = {
  CREATE_USER: "CREATE_USER",
  THROW_SIGN_UP_ERRORS: "THROW_SIGN_UP_ERRORS",
  REMOVE_SIGN_UP_ERRORS: "REMOVE_SIGN_UP_ERRORS",
  LOGIN_USER: "LOGIN_USER",
  THROW_LOGIN_ERROR: "THROW_LOGIN_ERROR",
  REMOVE_LOGIN_ERROR: "REMOVE_LOGIN_ERROR",
  LOGOUT_USER: "LOGOUT_USER",
  THROW_LOGOUT_ERROR: "THROW_LOGOUT_ERROR",
  REMOVE_LOGOUT_ERROR: "REMOVE_LOGOUT_ERROR",
};

export default types;
