const types = {
  CREATE_USER: "CREATE_USER",
  THROW_SIGN_UP_ERRORS: "THROW_SIGN_UP_ERRORS",
  LOGIN_USER: "LOGIN_USER",
  THROW_LOGIN_ERROR: "THROW_LOGIN_ERROR",
  REMOVE_LOGIN_ERROR: "REMOVE_LOGIN_ERROR",
};

export default types;
